time="2025-09-14T14:42:58+03:00" level=warning msg="C:\\Users\\gulsa\\federated-cancer-screening\\docker-compose.backend.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Container redis  Running
 Container postgres_db  Running
Attaching to backend_api, postgres_db, redis
backend_api  | [2025-09-14 11:43:01 +0000] [1] [INFO] Starting gunicorn 22.0.0
backend_api  | [2025-09-14 11:43:01 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend_api  | [2025-09-14 11:43:01 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
backend_api  | [2025-09-14 11:43:01 +0000] [7] [INFO] Booting worker with pid: 7
backend_api  | [2025-09-14 11:43:01 +0000] [8] [INFO] Booting worker with pid: 8
backend_api  | [2025-09-14 11:43:01 +0000] [9] [INFO] Booting worker with pid: 9
backend_api  | [2025-09-14 11:43:01 +0000] [10] [INFO] Booting worker with pid: 10
backend_api  | [2025-09-14 11:43:15 +0000] [8] [ERROR] Exception in worker process
backend_api  | Traceback (most recent call last):
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend_api  |     worker.init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend_api  |     super().init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend_api  |     self.load_wsgi()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend_api  |     self.wsgi = self.app.wsgi()
backend_api  |                 ^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend_api  |     self.callable = self.load()
backend_api  |                     ^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend_api  |     return self.load_wsgiapp()
backend_api  |            ^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend_api  |     return util.import_app(self.app_uri)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend_api  |     mod = importlib.import_module(module)
backend_api  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend_api  |     return _bootstrap._gcd_import(name[level:], package, level)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend_api  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend_api  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend_api  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend_api  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend_api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_api  |   File "/app/main.py", line 33, in <module>
backend_api  |     from . import crud
backend_api  | ImportError: attempted relative import with no known parent package
backend_api  | [2025-09-14 11:43:15 +0000] [8] [INFO] Worker exiting (pid: 8)
backend_api  | [2025-09-14 11:43:15 +0000] [9] [ERROR] Exception in worker process
backend_api  | Traceback (most recent call last):
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend_api  |     worker.init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend_api  |     super().init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend_api  |     self.load_wsgi()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend_api  |     self.wsgi = self.app.wsgi()
backend_api  |                 ^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend_api  |     self.callable = self.load()
backend_api  |                     ^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend_api  |     return self.load_wsgiapp()
backend_api  |            ^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend_api  |     return util.import_app(self.app_uri)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend_api  |     mod = importlib.import_module(module)
backend_api  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend_api  |     return _bootstrap._gcd_import(name[level:], package, level)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend_api  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend_api  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend_api  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend_api  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend_api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_api  |   File "/app/main.py", line 33, in <module>
backend_api  |     from . import crud
backend_api  | ImportError: attempted relative import with no known parent package
backend_api  | [2025-09-14 11:43:15 +0000] [9] [INFO] Worker exiting (pid: 9)
backend_api  | [2025-09-14 11:43:16 +0000] [7] [ERROR] Exception in worker process
backend_api  | Traceback (most recent call last):
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend_api  |     worker.init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend_api  |     super().init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend_api  |     self.load_wsgi()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend_api  |     self.wsgi = self.app.wsgi()
backend_api  |                 ^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend_api  |     self.callable = self.load()
backend_api  |                     ^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend_api  |     return self.load_wsgiapp()
backend_api  |            ^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend_api  |     return util.import_app(self.app_uri)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend_api  |     mod = importlib.import_module(module)
backend_api  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend_api  |     return _bootstrap._gcd_import(name[level:], package, level)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend_api  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend_api  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend_api  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend_api  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend_api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_api  |   File "/app/main.py", line 33, in <module>
backend_api  |     from . import crud
backend_api  | ImportError: attempted relative import with no known parent package
backend_api  | [2025-09-14 11:43:16 +0000] [7] [INFO] Worker exiting (pid: 7)
backend_api  | [2025-09-14 11:43:16 +0000] [10] [ERROR] Exception in worker process
backend_api  | Traceback (most recent call last):
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend_api  |     worker.init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend_api  |     super().init_process()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend_api  |     self.load_wsgi()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend_api  |     self.wsgi = self.app.wsgi()
backend_api  |                 ^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend_api  |     self.callable = self.load()
backend_api  |                     ^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend_api  |     return self.load_wsgiapp()
backend_api  |            ^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend_api  |     return util.import_app(self.app_uri)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend_api  |     mod = importlib.import_module(module)
backend_api  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend_api  |     return _bootstrap._gcd_import(name[level:], package, level)
backend_api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend_api  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend_api  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend_api  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend_api  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend_api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_api  |   File "/app/main.py", line 33, in <module>
backend_api  |     from . import crud
backend_api  | ImportError: attempted relative import with no known parent package
backend_api  | [2025-09-14 11:43:16 +0000] [10] [INFO] Worker exiting (pid: 10)
backend_api  | [2025-09-14 11:43:17 +0000] [1] [ERROR] Worker (pid:9) exited with code 3
backend_api  | [2025-09-14 11:43:17 +0000] [1] [ERROR] Worker (pid:10) was sent SIGTERM!
backend_api  | [2025-09-14 11:43:17 +0000] [1] [ERROR] Worker (pid:8) exited with code 3
backend_api  | Traceback (most recent call last):
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run
backend_api  |     self.sleep()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 360, in sleep
backend_api  |     ready = select.select([self.PIPE[0]], [], [], 1.0)
backend_api  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
backend_api  |     self.reap_workers()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
backend_api  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
backend_api  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
backend_api  | 
backend_api  | During handling of the above exception, another exception occurred:
backend_api  | 
backend_api  | Traceback (most recent call last):
backend_api  |   File "/usr/local/bin/gunicorn", line 8, in <module>
backend_api  |     sys.exit(run())
backend_api  |              ^^^^^
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
backend_api  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
backend_api  | [2025-09-14 11:43:17 +0000] [1] [ERROR] Worker (pid:7) was sent SIGTERM!
backend_api  |     super().run()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
backend_api  |     Arbiter(self).run()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 229, in run
backend_api  |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 342, in halt
backend_api  |     self.stop()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 396, in stop
backend_api  |     time.sleep(0.1)
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
backend_api  |     self.reap_workers()
backend_api  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
backend_api  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
backend_api  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[Kbackend_api exited with code 1
